// <auto-generated />
using System;
using ChefsDishes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChefsDishes.Migrations
{
    [DbContext(typeof(DishContext))]
    [Migration("20181210185511_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChefsDishes.Chef", b =>
                {
                    b.Property<int>("chefid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("birthday");

                    b.Property<string>("firstname");

                    b.Property<string>("lastname");

                    b.HasKey("chefid");

                    b.ToTable("Chefs");
                });

            modelBuilder.Entity("ChefsDishes.Dish", b =>
                {
                    b.Property<int>("dishid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("calories");

                    b.Property<int>("chefid");

                    b.Property<string>("description");

                    b.Property<string>("name");

                    b.Property<int>("tastiness");

                    b.HasKey("dishid");

                    b.ToTable("Dishes");
                });
#pragma warning restore 612, 618
        }
    }
}
