// <auto-generated />
using System;
using ChefsDishes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChefsDishes.Migrations
{
    [DbContext(typeof(DishContext))]
    partial class DishContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChefsDishes.Chef", b =>
                {
                    b.Property<int>("chefid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("birthday");

                    b.Property<string>("firstname");

                    b.Property<string>("lastname");

                    b.HasKey("chefid");

                    b.ToTable("Chefs");
                });

            modelBuilder.Entity("ChefsDishes.Dish", b =>
                {
                    b.Property<int>("dishid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("calories");

                    b.Property<int>("chefid");

                    b.Property<string>("description");

                    b.Property<string>("name");

                    b.Property<int>("tastiness");

                    b.HasKey("dishid");

                    b.HasIndex("chefid");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("ChefsDishes.Dish", b =>
                {
                    b.HasOne("ChefsDishes.Chef", "Chefwhomade")
                        .WithMany("dish")
                        .HasForeignKey("chefid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
